name: "Infrastructure Deployment"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: "us-east-1"
      
      # Senior Tip: Inject secrets as TF_VARs so Terraform can use them
      TF_VAR_mongo_uri: ${{ secrets.MONGO_URI }}
      TF_VAR_aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
      TF_VAR_aws_region: "us-east-1"
      TF_VAR_ami_id: "ami-04b70fa74e45c3917"

      TF_VAR_environment: "dev"

      
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false 

      - name: Terraform Init
        run: terraform init -input=false
        working-directory: ./terraform

      - name: Terraform Format Check
        # If this fails, run 'terraform fmt -recursive' locally and push
        run: terraform fmt -check
        working-directory: ./terraform

      - name: Terraform Plan
        id: plan
        run: terraform plan -input=false
        working-directory: ./terraform

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false
        working-directory: ./terraform
